server:
  port: 8080

spring:
  application:
    name: car-rental-api-gateway

  cloud:
    gateway:
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
    
      routes:
        - id: car-rental-user-service
          uri: lb://car-rental-user-service
          predicates:
            - Path=/api/user/**

        - id: car-rental-booking-service
          uri: lb://car-rental-booking-service
          predicates:
            - Path=/api/booking/**
        
        - id: car-rental-car-service
          uri: lb://car-rental-car-service
          predicates:
            - Path=/api/car/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka